import React from "react";
import Link from "next/link";
import { User, LogOut } from "lucide-react";
import { UserRound } from 'lucide-react'; // icons from lucide-react

export const metadata = {
  title: "Account",
  description: "Generated by create next app",
};

function Page() {
  const navItems = [
    { name: "Profile", href: "/account/profile", icon: <User size={18} /> },
    { name: "Logout", href: "/account/logout", icon: <LogOut size={18} /> },
  ];

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-100 to-gray-200 p-4">
      <div className="bg-white rounded-3xl shadow-2xl p-8 w-full max-w-md space-y-6">
        <div className="text-center">
        <div className="w-20 h-20 mx-auto rounded-full bg-indigo-100 flex items-center justify-center">
  <UserRound size={36} className="text-gray-600" />
</div>
          <h1 className="text-3xl font-extrabold mt-4 text-gray-800">Account</h1>
          <p className="text-gray-500 text-sm">Manage your profile and settings</p>
        </div>

        <ul className="space-y-4">
          {navItems.map(({ name, href, icon }) => (
            <li key={name}>
              <Link
                href={href}
                className="flex items-center gap-3 justify-center bg-gray-800 hover:bg-gray-600 text-white font-semibold py-3 px-6 rounded-xl transition duration-300"
              >
                {icon}
                <span>{name}</span>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default Page;
